Eshop/Models/Admin/Category/CategoryEditCreateModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Eshop.Models.Admin.Category
{
    public class CategoryEditCreateModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int ParentCategoryId { get; set; }

        public IList<Microsoft.AspNetCore.Mvc.Rendering.SelectListItem> CategoryNames { get; set; }
    }
}

Eshop/Models/Admin/Category/CategoryViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Eshop.Models.Admin.Category
{
    public class CategoryViewModel : BaseModel
    {
        //[Required]
        public string Name { get; set; }
        public int ParentCategoryId { get; set; }
        public string ParentCategoryName { get; set; }
        
    }
}

Eshop/Controllers/AdminControllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Eshop.Infrastructure.Orchestrator;
using Eshop.Models;
using Eshop.Models.Admin.Category;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Eshop.Controllers.EshopControllers
{
    public class CategoryController : AdminBaseController
    {
        private readonly ICategoryOrchestrator _orchestrator;

        public CategoryController(ICategoryOrchestrator orchestrator)
        {
            this._orchestrator = orchestrator;            
        }

        // GET: /<controller>/
        public IActionResult Index()
        {
            var model = _orchestrator.GetAllCategories();
            return ToView(model);
        }

        [HttpGet]
        public IActionResult Create()
        {
            var categories = _orchestrator.GetAllCategories();

            var model = new CategoryEditCreateModel() { CategoryNames = new List<Microsoft.AspNetCore.Mvc.Rendering.SelectListItem>() { new Microsoft.AspNetCore.Mvc.Rendering.SelectListItem() { Value = "0", Text = "" } } };
            foreach (var item in categories)
            {
                model.CategoryNames.Add(new Microsoft.AspNetCore.Mvc.Rendering.SelectListItem() {
                    Text = item.Name,
                    Value = item.Id.ToString()                    
                });
            }


            return ToView(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(CategoryEditCreateModel model)
        {
            //if(ModelState.IsValid)
            //{
            //    var result = _orchestrator.CreateCategory(model);
            //    if (result.Success)
            //        return RedirectToAction("Index");
            //}
            var result = _orchestrator.CreateCategory(model);
            if (result.Success)
                return RedirectToAction("Index");

            return ToView(model);
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            Infrastructure.OperationResult result = _orchestrator.DeleteCategory(id);
            if (result.Success)
                return RedirectToAction("Index");

            return ToView();
        }

        [HttpGet]
        public IActionResult Update(int id)
        {
            var categories = _orchestrator.GetAllCategories();
            var category = categories.Where(t => t.Id == id).FirstOrDefault();

            var model = new CategoryEditCreateModel() {
                Id = category.Id,
                Name = category.Name,
                ParentCategoryId = category.ParentCategoryId,                
                CategoryNames = new List<Microsoft.AspNetCore.Mvc.Rendering.SelectListItem>() {
                    new Microsoft.AspNetCore.Mvc.Rendering.SelectListItem() { Value = "0", Text = "" }
                }
            };
            
            foreach (var item in categories)
            {
                model.CategoryNames.Add(new Microsoft.AspNetCore.Mvc.Rendering.SelectListItem()
                {
                    Text = item.Name,
                    Value = item.Id.ToString(),
                    Selected = model.ParentCategoryId == item.Id
                });
            }

            return ToView(model, "Create");
        }

        [HttpPost]
        public IActionResult Update(CategoryEditCreateModel model)
        {
            Infrastructure.OperationResult result = _orchestrator.UpdateCategory(model);
            if (result.Success)
                return RedirectToAction("Index");

            return ToView(model, "Create");
        }

    }
}

Eshop/Views/Admin/Category/Create.cshtml
@model Eshop.Models.Admin.Category.CategoryEditCreateModel
@{
    Layout = ViewData["Layout"].ToString();
    string postMethod = "";
    if (string.IsNullOrEmpty(Model.Name))
    {
        postMethod = "Create";
    }
    else
    {
        postMethod = "Update";
    }
    

    

}
@using (Html.BeginForm(postMethod, "Category", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    <div class="form-group">
        <label for="category-name">Category name: </label>        
        @Html.TextBoxFor(t => t.Name, new { @class = "form-control", placeholder = "Enter category name" })
        @Html.ValidationMessageFor(t => t.Name)        
    </div>
    <div class="form-group">
        <label for="category-parent">Parent</label>
        @Html.DropDownListFor(t => t.ParentCategoryId, Model.CategoryNames, new { @class = "form-control" })

    </div>
    @Html.HiddenFor(t => t.Id, Model.Id)
    <button type="submit" class="btn btn-primary">Submit</button>
}

Eshop/Views/Admin/Category/Index.cshtml
@model IList<Eshop.Models.Admin.Category.CategoryViewModel>

@{
    Layout = ViewData["Layout"].ToString();
}

<div class="admin-category-add">
    <h2>Categories</h2>
    <input type="text" placeholder="Search..." class="form-control mx-sm-3" id="search" />
    <a href="@Url.Action("Create", "Category")" class="btn btn-success">Create</a>
</div>


<table class="table table-striped table-dark">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Category</th>
            <th scope="col">Parent</th>
            <th scope="col">Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Id</td>
                <td>@item.Name</td>
                <td>@item.ParentCategoryName</td>
                <td>
                    @Html.ActionLink("Edit", "Update", "Category", new { id = item.Id }, new { @class = "btn btn-warning" })
                    <a href="#" onclick="window.confirm('Are you sure?')? window.location.href = 'Category/Delete/@item.Id': ''" class="btn btn-danger">Delete</a>
                </td>
            </tr>
        }      
    </tbody>
</table>